name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # 00:00 on Saturdays
    - cron: '0 0 * * SAT'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jest-version: [24, 25, 26, 27, latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - run: yarn --frozen-lockfile

      - run: yarn add jest@${{ matrix.jest-version }}

      - name: Test on Jest@${{ matrix.jest-version }}
        run: yarn test
