name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - run: npm ci

      - run: npm run test
